msgfmt -o ..\Binary\cs.mo ..\Poedit\cs.po
msgfmt -o ..\Binary\de_DE.mo ..\Poedit\de_DE.po
msgfmt -o ..\Binary\es_lat.mo ..\Poedit\es_lat.po
msgfmt -o ..\Binary\fr.mo ..\Poedit\fr.po
msgfmt -o ..\Binary\it.mo ..\Poedit\it.po
msgfmt -o ..\Binary\pl.mo ..\Poedit\pl.po
msgfmt -o ..\Binary\pt_BR.mo ..\Poedit\pt_BR.po
msgfmt -o ..\Binary\ru.mo ..\Poedit\ru.po
msgfmt -o ..\Binary\fa.mo ..\Poedit\fa.po
